mountinfo: TestMountedBy: require root
This test needs root as its setup performs some mounts.
It used to require root (indirectly via requireOpenat2),
but after commit 098ed008148 this is no longer the case,
and thus if passwordless sudo is not available, the test
fails:

	[kir@kir-rhat sys]$ make test
	sudo: a password is required
	for p in mountinfo mount signal symlink; do \
		(cd $p && go test  -v .); \
	done
	=== RUN   TestMountedBy
	    mounted_linux_test.go:221: setup failed: mount /tmp/TestMountedBy1220310657/tmpfs-mount: operation not permitted
	--- FAIL: TestMountedBy (0.00s)

Add an explicit root check to fix this.

Fixes: 098ed008148
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>