mountinfo: fix windows build
When compiling for windows, we get this error:

> GOOS="windows" GOARCH="amd64" GOARM=""
> vendor/github.com/moby/sys/mountinfo/mountinfo.go:16:9: undefined: parseInfoFile

The problem is newly added GetMountsFromReader().

Amend the _windows.go and _unsupported.go to fix.

NOTE that eventually we need to deprecate windows support for this
library, since it's not really doing anything.

Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>