mount: fix test for added relatime
The mount option `relatime` can be added by the kernel, and
this is what happens on my machine:

> --- FAIL: TestMount (0.00s)
>     mounter_linux_test.go:176: unexpected mount option "relatime", expected ""
> FAIL

Same as in commit afc7b0dd970, this option should be ignored.

Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>