mount: fix tests for kernel 5.9+
I am seeing the following failures on my machine (running):

	=== RUN   TestMount/none-remount,size=128k
	    mounter_linux_test.go:203: unexpected vfs option "inode64", expected "rw,size=128k"
	=== RUN   TestMount/none-remount,ro,size=128k
	    mounter_linux_test.go:203: unexpected vfs option "inode64", expected "ro,size=128k"
	--- FAIL: TestMount (0.06s)

Looking into /proc/self/mountinfo, I see that all tmpfs mounts have this
option. Looking into the kernel, it was added by commit ea3271f7196c6
("tmpfs: support 64-bit inums per-sb", 2020-08-06), which made its way
into v5.9-rc1.

Ignore the option, as well as "inode32".

Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>