Makefile: test-local: skip if go version is not supported
While some modules support go1.18, they may not be when updating the
dependency to later versions, which can happen when using the "local"
versions.

Check if both packages support the Go version used for the test, and
skip kip testing those packages if the Go version is not supported after
updating to the latest version of the dependency.

    echo 'replace github.com/moby/sys/sequential => ../sequential' | cat atomicwriter/go.mod - > atomicwriter/go-local.mod
    # Run go mod tidy to make sure sequential dependency versions are met.
    cd atomicwriter && go mod tidy -modfile=go-local.mod && go test -modfile=go-local.mod  -v .
    go: downloading golang.org/x/sys v0.37.0
    # golang.org/x/sys/windows
    Error: C:\Users\runneradmin\go\pkg\mod\golang.org\x\sys@v0.37.0\windows\security_windows.go:1318:39: undefined: unsafe.SliceData
    Error: C:\Users\runneradmin\go\pkg\mod\golang.org\x\sys@v0.37.0\windows\security_windows.go:1321:39: undefined: unsafe.SliceData
    Error: C:\Users\runneradmin\go\pkg\mod\golang.org\x\sys@v0.37.0\windows\security_windows.go:1324:40: undefined: unsafe.SliceData
    Error: C:\Users\runneradmin\go\pkg\mod\golang.org\x\sys@v0.37.0\windows\security_windows.go:1327:40: undefined: unsafe.SliceData
    note: module requires Go 1.24
    FAIL	github.com/moby/sys/atomicwriter [build failed]
    FAIL
    make: *** [Makefile:46: test-local] Error 2
    Error: Process completed with exit code 2.

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>